# Generated by Django 4.0.5 on 2022-12-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('mobile', models.CharField(max_length=12)),
                ('date_of_birth', models.DateField()),
                ('gpa', models.FloatField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('level', models.CharField(choices=[('1', 'Level One'), ('2', 'Level Two'), ('3', 'Level Three'), ('4', 'Level Four')], max_length=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('IS', 'Information Systems'), ('IT', 'Information Technology'), ('AI', 'Artificial Intelligence'), ('DS', 'Operation Research and Decision Support')], max_length=2)),
            ],
        ),
    ]
